export const SET_IS_INGREDIENT_MODAL_OPEN = 'SET_IS_INGREDIENT_MODAL_OPEN'
export const SET_IS_ORDER_MODAL_OPEN = 'SET_IS_ORDER_MODAL_OPEN'
export const SET_IS_ERROR_MODAL_OPEN = 'SET_IS_ERROR_MODAL_OPEN'
