export const API_BASE_URL = 'https://norma.nomoreparties.space/api'

// reducer cases
export const SET_ALL_INGREDIENTS = 'SET_ALL_INGREDIENTS'
export const SET_ORDER_DETAILS = 'SET_ORDER_DETAILS'
export const SET_LOADER_STATUS = 'SET_LOADER_STATUS'
export const PICK_BUN = 'PICK_BUN'
export const PICK_PRIMARY_INGREDIENTS = 'PICK_PRIMARY_INGREDIENTS'
export const UPDATE_ORDER_SUM = 'UPDATE_ORDER_SUM'
export const UPDATE_ORDER_INGREDIENTS_ID = 'UPDATE_ORDER_INGREDIENTS_ID'
